### ISSUE TITLE
Push tags to the fork as well

### ISSUE THREAD

**Issue by JelteF** [jteeuwen/go-bindata#1]
Some dependency tools rely on them.

**Comment by a-urth** [comment]
Do You know what happened to old repo?

**Comment by jteeuwen** [comment]
@a-urth As you know, it's disappeared, so I sign up the new account and fork repo from yours. I don't know where the old repo is.

**Comment by jteeuwen** [comment]
@JelteF done.

**Comment by JelteF** [comment]
Thanks, using our own fork at the moment though.
