### ISSUE TITLE
Bindata file is always written even if unchanged

### ISSUE THREAD

**Issue by leehambley** [jteeuwen/go-bindata#120]
Stub issue to ask if you would accept a patch, or consider this valid behaviour.

We currently have a setup that `go generate` triggers our `go-bindata` build - if we don't touch the source files that are compiled, and then re-run `go generate` the modification time of the bindata file is updated to the current time. 

I believe since the file isn't changed (same bytes overwritten) this is incorrect, and this incorrect because it causes `go install` to repeat a lot of useless work (specifically the linking, which takes 30s in our project). 

The problem is different on go 1.4 (which always links, regardless) or go 1.5, which only links on changes. Either solution is bad, since compilation is 3x slower for us on 1.5, it would be worth to upgrade, though 1.5 is slower to compile, since it doesn't do useless linker work (but only if this issue would be fixed)

I'd propose diff'ing (sha1?) the hash of the intenral file buffer with the reloaded file on disk, if they don't differ, don't write the file ?

**Comment by jteeuwen** [comment]
If nobody else objects, I'm ok with your suggestion.

**Comment by leehambley** [comment]
I made a start on this, can't say when I'll be done, the code is a little … disorganized! Thanks for accepting a PR I hope it'll be mergeable.

**Comment by benma** [comment]
:+1: 

Any progress on this?

**Comment by rayzyar** [comment]
Any progress? 👍
