### ISSUE TITLE
New Semantic Version

### ISSUE THREAD

**Issue by tehsphinx** [jteeuwen/go-bindata#13]
Can we get a new semantic version on this repo?

3.0.7 is the latest version in this repo but it does not contain `MustAsset` function. Since 3.0.7 is the latest version `go modules` falls back to it breaking my code.

**Comment by tehsphinx** [comment]
Here is the workaround to get the latest version (with go modules enabled):
```
go get github.com/jteeuwen/go-bindata@master
```

Would still be nice to update this repo to be compatible with go modules. Right now it is not as it's version is >1 and it does not have a `go.mod` file.

See https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by FranklinYu** [comment]
This repository would be archived, Sorry. Discussion should be in https://github.com/jteeuwen/discussions. You can also find other maintained forks there.
