### ISSUE TITLE
Ignore date flag?

### ISSUE THREAD

**Issue by colemickens** [jteeuwen/go-bindata#142]
Would you accept a PR to add a flag to write out a dummy date instead of the real modification date?

**Comment by martinlindhe** [comment]
Maybe `-nometadata` is what you need?

From --help:
```
  -nometadata
    	Assets will not preserve size, mode, and modtime info.
```

**Comment by colemickens** [comment]
Yeah, I'm actually using this flag since filing this. Time to close. Thanks.
