### ISSUE TITLE
Write atomically

### ISSUE THREAD

**Issue by kevinburke** [jteeuwen/go-bindata#168]
We write assets/bindata.go (or whatever your file is named) by creating a bufio.NewWriter and writing to it.

This means it's possible for some other program to read a half-written file.

It would be a better idea to instead write to a temporary file, and then call os.Rename to atomically modify the asset file in question.

**Comment by komuW** [comment]
This seems to be an abandoned project. 
this -> https://github.com/tmthrgd/go-bindata seems like a fork that is active. 
@kevinburke maybe you could open an issue there

**Comment by komuW** [comment]
Also see this issue, https://github.com/jteeuwen/go-bindata/issues/165 that discusses the project's status and alternatives

**Comment by kevinburke** [comment]
I went ahead and implemented this myself in https://github.com/kevinburke/go-bindata/commit/d92efe3dbdfb978c90cbc1522e2862b1ea1ae2b8. Going to close.
