### ISSUE TITLE
High Sierra Update

### ISSUE THREAD

**Issue by plamenGo** [jteeuwen/go-bindata#170]
Hi, I keep getting these errors when I run go-bindata after installing MacOS High-Sierra. 

Any idea what I should try to fix this?

resources/get.go:1: running "go-bindata": signal: segmentation fault
templates/get.go:1: running "go-bindata": signal: segmentation fault
Failed run command: go
exit status 1

**Comment by plamenGo** [comment]
had to reinstall go-bindata

**Comment by vjeantet** [comment]
thanks for writing down your issue, it saved me some hours :)
