### ISSUE TITLE
Import other repos from jteeuwen as well

### ISSUE THREAD

**Issue by muesli** [jteeuwen/go-bindata#2]
I have copies of `go-pkg-rss` and `go-pkg-xmlx` locally.

**Comment by muesli** [comment]
I've uploaded them to https://github.com/muesli/go-pkg-xmlx and https://github.com/muesli/go-pkg-rss

**Comment by mewmew** [comment]
Also `framebuffer`. Ref gen2brain/goiv#1

**Comment by FranklinYu** [comment]
This repository will be archived. For all the discussion please go to <https://github.com/jteeuwen/discussions>.
