### ISSUE TITLE
Support for symlinks?

### ISSUE THREAD

**Issue by sent-hil** [jteeuwen/go-bindata#24]
I get `open file.js: no such file or directory`, however the file is exists and is a symlink.

**Comment by abates** [comment]
I'm curious if there has been any movement on this issue?  I just ran into a situation where including symlinks would be very helpful.

**Comment by shurcooL** [comment]
> I just ran into a situation where including symlinks would be very helpful.

Can you describe that situation please?

**Comment by abates** [comment]
@shurcooL: when serving development content I have a tmp directory.  The tmp directory includes file that are automatically build (less to css for instance) or updated (injections in index.html).  It also has symlinks to other content (images and bower_components for instance).  I don't want to create copies of those resources, so having go-bindata be able to read from the linked directories is nice.  

Looks like @jteeuwen merged my updates for this feature and it's working for me :)

**Comment by shurcooL** [comment]
I see, thanks!
