### ISSUE TITLE
Please document history, state and intention of this account and project

### ISSUE THREAD

**Issue by jwkohnen** [jteeuwen/go-bindata#3]
There is a discussion on [/r/golang](https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/) about this repository and potentially there will be further debate about the history of this repository as it resembles the infamous incidents of left-pad et seqq. 

I speculate that this repository is controlled by @a-urth but no one knows. Since the original repository was in a desolate state and was abandoned for two years, it would be great to document the intentions and possible road map of this doppelgänger. 

Please consider to mark this repository as a deprecated archive or to convert this account to an organization that transforms this project to something reliable (which it currently and obviously is not).

**Comment by a-urth** [comment]
This one is run not by me. I'm intentionally created new one under my personal account.

**Comment by skymeyer** [comment]
@a-urth there is a maintained fork for `go-bindata` at https://github.com/kevinburke/go-bindata. We switched last night on https://github.com/bazelbuild/rules_go/pull/1308.

I'd recommend indeed as mentioned by @wjkohnen to flag this as a deprecated archive.

**Comment by FranklinYu** [comment]
Guys, how do you see fit? New issue or README (which means new commit in master branch)?

I’ll do a new issue first. If we later decide to change the README, I can do it afterwards.

**Comment by FranklinYu** [comment]
Update: see #5.

**Comment by tombh** [comment]
From my digging through the fork graphs  a few weeks ago before the deletion it seemed, https://github.com/shuLhan/go-bindata was the most up to date and maintained.

**Comment by FranklinYu** [comment]
This repository will be archived. Please go to <https://github.com/jteeuwen/discussions> for discussion.
