### ISSUE TITLE
Announcement and disclosure

### ISSUE THREAD

**Issue by FranklinYu** [jteeuwen/go-bindata#5]
I’m a friend of the repo owner. The current owner is not the original jteeuwen, and we have no relation with him, nor do we want to take any credit. We have no way to know what happened to jteeuwen.

The intention of this account and repo was simply to fix the building of a private project. The current owner had no way to directly redirect the repo, so he made such work-around so that he could safely go home without being blamed by his supervisor. And of course, hoped this would also save someone else trapped in similar situation.

Current status of this repo is the latest snapshot he has (and probably the latest snapshot). We do not intend to update this repo so far, since that is beyond our intention. There is some pretty good forks out there, well-maintained.

Sorry for the mess, and hope this didn’t hurt anyone.

Update: see gofrs/help-requests#7.

**Comment by mmlb** [comment]
This repo should therefore be archived to better show the intent of the resurrection. Archived repos are readonly and still cloneable. https://help.github.com/articles/archiving-a-github-repository/

**Comment by FranklinYu** [comment]
@mmlb Archiving this repository means we cannot create new issue, or comment on current issues (including this one). There is not enough discussion for us to decide how to deal with #2 (only 4 visible participants), so I think I shall at least leave issues open.

**Comment by mmlb** [comment]
@franklinyu those 2 packages in #2 have nothing to do with this repository and I don't think any new issues should be opened here. I would suggest creating a gitter.im room, update the repo blurb to point to gitter for discussing jteeuwen packages and then archiving this repo. #2 has 2 participants and 2 thumbs, this has 38 thumbs and doesn't keep this repo looking like its alive for further than necessary.

**Comment by mychkin** [comment]
those 2 repos are missing as well:

github.com/jteeuwen/go-pkg-rss
github.com/jteeuwen/go-pkg-xmlx

**Comment by liweiv** [comment]
I had built a go-bindata organization to maintain this project from this branch. 
 https://github.com/go-bindata/go-bindata

**Comment by FranklinYu** [comment]
Ok guys, this repository will be archived. For all the discussion please go to <https://github.com/jteeuwen/discussions>.

**Comment by T-Pham** [comment]
So anyone knows what happened to the original owner?
