### ISSUE TITLE
go vet part of go now

### ISSUE THREAD

**Issue by tvmaly** [jteeuwen/go-bindata#6]
when I attempt to run make

I get an error message as it tries to download vet even though vet is part of go now:

make
make -C testdata
go get github.com/kisielk/errcheck
go get golang.org/x/tools/cmd/vet
package golang.org/x/tools/cmd/vet: cannot find package "golang.org/x/tools/cmd/vet" in any of:
	/usr/local/go/src/golang.org/x/tools/cmd/vet (from $GOROOT)
	/Users/tmaly/godev/src/golang.org/x/tools/cmd/vet (from $GOPATH)
make[1]: *** [vet] Error 1
make: *** [all] Error 2

**Comment by FranklinYu** [comment]
This repository will be archived. For all the discussion please go to <https://github.com/jteeuwen/discussions>.

**Comment by tvmaly** [comment]
No worries,  I have moved over to using https://github.com/tmthrgd/go-bindata
