### ISSUE TITLE
function ends without a return statement?

### ISSUE THREAD

**Issue by lazydino** [jteeuwen/go-bindata#65]
Hi, 

Why is the install command 
go get github.com/jteeuwen/go-bindata/... causing

/usr/lib/go/src/pkg/github.com/jteeuwen/go-bindata/toc.go:48: function ends without a return statement
?
I am running go on Ubuntu 12

**Comment by shurcooL** [comment]
Whoops, I accidentally looked inside a wrong folder. There is a `toc.go` file in the root folder after all.

That confirms you have an extremely outdated version of Go, older than 1.1. You should really update to a modern version of Go.

**Comment by lazydino** [comment]
Thanks!, I think I am running 1.0, will update my Go to 1.4
