### ISSUE TITLE
Intent to fork, simplify and work on specialized feature development.

### ISSUE THREAD

**Issue by shurcooL** [jteeuwen/go-bindata#75]
Hi @jteeuwen and @elazarl.

First off, a huge thank you for making this useful library. Recently I've started using `go-bindata` in tandem with `go-bindata-assetfs` to embed asset files inside a Go binary web server. Combined with `go generate` directives, it's both convenient and powerful.

After using it for a bit, I've learned what works well and what doesn't, and what improvements I want for this library. My use case is to make a virtual file system available as output. But I want to make virtual file system as the library's input as well. I also want to tackle #22. I also want to merge debug and dev modes and in fact remove them, since in development `http.Dir("./assets/")` can be used as the virtual file system.

By using those 2 libraries, I see there's a lot of overlap between functionality between them, which causes some inefficiency and also makes some things I want to do not easy/possible.

I was thinking how to best contribute my changes, but I think at this time the best course of action is for me to make a fork with a separate API. This `go-bindata` library likely has a lot of users that depend on its current API, so I think a separate package makes most sense for now. Later on, we can always merge efforts as needed.

My fork will combine the functionality of those two libraries into one. It will be opinionated and focus on trimming out all that I don't find necessary for my specific use case, and aim for efficiency in terms of performance. I also want the freedom to experiment with APIs and see what works best in this problem space.

So, just wanted to update you on that. This forked library will be open source and available for anyone who wants to use it.

Thanks!

**Comment by elazarl** [comment]
Hi @shurcooL ,

Have you considered [go.rice](https://github.com/GeertJohan/go.rice).

Sounds very similar to what you have in mind.

In fact, had I known about it, I'd probably wouldn't develop `go-bindata-assetfs`.

I really think that if rice solves your problems, you'd better spend your efforts on other endeavors.

Thanks!

**Comment by shurcooL** [comment]
I've seen `go.rice` and I have considered it, but I wasn't a big fan of its API. It seems capable, but what I want is a more simple pure virtual filesystem abstraction rather than a custom API (which is pretty close to a VFS admittedly). Also, it seems to use zip rather than gzip compression, which isn't compatible with most browsers if I understand correctly.

Thanks for the suggestion though!

**Comment by elazarl** [comment]
As far as I understand, rice uses zip only for some embedding methodology.

If I were you, I'd think well if yet-another library, with slightly better API, would serve everyone better than improving on current state. `go.rice` is very similar to what you have in mind, and I think you should consider, e.g., adding gzip support to rice. I'll be more than happy to add `os.Filesystem` interface to go-bindata-assetfs.

**Comment by shurcooL** [comment]
> If I were you, I'd think well if yet-another library, with slightly better API, would serve everyone better than improving on current state.

I understand, and I've thought hard about this. The API and approach I have planned is significantly different that I cannot just make incremental improvements at this time.

> I'll be more than happy to add `os.Filesystem` interface to go-bindata-assetfs.

I'm not sure I follow. There is no `os.Filesystem` interface, and `go-bindata-assetfs` already implements `http.FileSystem`.

**Comment by elazarl** [comment]
I was thinking about
https://talks.golang.org/2012/10things.slide#8
or
https://godoc.org/golang.org/x/tools/godoc/vfs#FileSystem

**Comment by shurcooL** [comment]
Some notes on the choice of virtual filesystem interface to go with.

When I had this idea, I considered `vfs.FileSystem` to be a superior/more modern interface to implement and that was another thing I wanted to do differently. In the process of implementing it, I realized that for certain things, `http.FileSystem` style is actually better.

Namely, if you want to implement a dynamic VFS that performs some calculations, it's better to return a single `http.File` which can be read and stated. Whereas `vfs.FileSystem` forces you to implement `Stat` method separately from `Open`, so the computation would need to be happen twice; once when `Stat` is called to determine the result file size, and second time when the actual file contents are needed for access.

I was only able to learn that through experimentation and trial/error.

**Comment by shurcooL** [comment]
This is done now. I haven't announced it properly yet, but here it is:

[`github.com/shurcooL/vfsgen`](https://github.com/shurcooL/vfsgen) - Package vfsgen generates a vfsdata.go file that statically implements the given virtual filesystem.

It's very simple and minimalistic, but it does what I need and it will allow me to build some things on top of it that I have planned.

Thank you both @jteeuwen and @elazarl for the starting code bases and permission to base my work on top of yours!
