### ISSUE TITLE
Generate tests for bindata.go

### ISSUE THREAD

**Issue by Luzifer** [jteeuwen/go-bindata#88]
In order to have the test coverage maximized the `go-bindata` tool should generate a `bindata_test.go` which covers the `bindata.go` routines with tests. In that case not every single coder has to write his own tests but automatically gets tests generated.

**Comment by mpictor** [comment]
IMO for generated code it's more important to test the generator (in this case, go-bindata) while it's being built, rather than testing its output at some later time. After all, you'll have to go back and modify the generator in the unlikely event that there _is_ a problem.

**Comment by shurcooL** [comment]
Highly agree with @mpictor. It makes a lot more sense to test code generation and the generated code inside this repo, rather than generating tests for go-bindata within user projects.

**Comment by hachi8833** [comment]
+1
