### ISSUE TITLE
Invalid Generated Go Code With Certain Filenames

### ISSUE THREAD

**Issue by nadams** [jteeuwen/go-bindata#89]
Embedding files that start with a `.` generates invalid go code.

A git bisect shows that the problem was introduced in commit dfcf23b04ef0cacd524a25ea18fbeede2d3bbcbb

I'm pretty sure the issue was introduced with the pull request jteeuwen/go-bindata#86
Specifically, this line was removed: https://github.com/jteeuwen/go-bindata/commit/dfcf23b04ef0cacd524a25ea18fbeede2d3bbcbb#diff-76b9265a0c3cccec7fb95e6bde2f273aL204

Here is some example output:
> assets/assets.go:387: syntax error: unexpected ., expecting (
> assets/assets.go:389: non-declaration statement outside function body
> assets/assets.go:390: non-declaration statement outside function body
> assets/assets.go:393: non-declaration statement outside function body
> assets/assets.go:395: non-declaration statement outside function body
> assets/assets.go:398: non-declaration statement outside function body
> assets/assets.go:400: non-declaration statement outside function body
> assets/assets.go:401: non-declaration statement outside function body
> assets/assets.go:402: syntax error: unexpected }

Example generated function name:
```go
func layoutsBase.ignore() (*asset, error) { ... }
```
go-bindata 3.1.0 (Go runtime go1.4.2).

**Comment by shurcooL** [comment]
We are hitting this issue as well, and I am also suspecting it's a regression coming from #86.
