### ISSUE TITLE
Not detecting any filename contains 'Category' word

### ISSUE THREAD

**Issue by riyan10dec** [jteeuwen/go-bindata#9]
i'm using go-bindata to generate my .graphql file to bindata.go as mentioned [here](https://github.com/OscarYuen/go-graphql-starter).

So, I create my .graphql file 'category.graphql', then run this command 

> go-bindata -ignore=\.go -pkg=schema -o=schema/bindata.go schema/...

my other .graphql file generated in bindata.go, but category.graphql. 
Then I try to change filename to merchant-category.graphql and run command above, but still not generated in bindata.go.
Then I change to merchant-cat.graphql and run command above, and it successfully generated.

So, is 'category' keyword is reserved keyword or something? If yes, if there any another reserved keyword?

Thanks for help.

**Comment by FranklinYu** [comment]
Please post your ideas [here](https://github.com/jteeuwen/discussions/issues), as mentioned in README.

In addition, this project is not maintained any more. Please consider asking the author to migrate away.
